- name: Homebrew Missing
  when: homebrew_present is not defined or not homebrew_present
  ansible.builtin.fail: 
    msg: "Expected homebrew to be configured."

- name: Install Workstation Packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - "azure-cli"

- name: Install Workstation Casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - "1password"
    - "hammerspoon"
    - "homebrew/cask-fonts/font-monaspace-nerd-font"
    - "homebrew/cask-fonts/font-monaspace"
    - "homebrew/cask-fonts/font-victor-mono-nerd-font"
    - "homebrew/cask-fonts/font-victor-mono-nerd-font"
    - "homebrew/cask-fonts/font-victor-mono"
    - "homebrew/cask-fonts/font-victor-mono"
    - "iterm2"
    - "jetbrains-toolbox"
    - "linear-linear"
    - "loom"
    - "microsoft-edge"
    - "miro"
    - "notion"
    - "raycast"
    - "spotify"
    - "visual-studio-code"
    - "zoom"

- name: Prep Hammerspoon Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ lookup('env', 'HOME') }}/.hammerspoon"
    - "{{ lookup('env', 'HOME') }}/.hammerspoon/Spoons"

- name: Install Hammerspoon Spoons
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: "{{ lookup('env', 'HOME') }}/.hammerspoon/Spoons" 
    remote_src: true
  with_items:
    - name: MiroWindowsManager.spoon
      src: https://github.com/miromannino/miro-windows-manager/raw/faa6f5f0bc025cc2465f3198609d2123d86101c2/MiroWindowsManager.spoon.zip