#!/bin/bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
cd $root
source "$root/script/helpers/_utils.sh"

ensure_bootstrapped

while [[ $# -gt 0 ]]; do
    key="$1"
    shift
    case "$key" in
        -d|--debug)
            enable_debug
            ;;
        *)
            select_host "$key"
            ;;
    esac
done
debug "Ansible Args: $fleet_ansible_args"

echo "Applying configuration for host '$fleet_target_host'"

source .venv/bin/activate
ansible-galaxy install -r requirements.yaml
ansible-playbook -K -i inventory.yaml "${fleet_ansible_args[@]}" --limit "$fleet_target_host" site.yaml
