#!/bin/bash
#/ Usage: script/bootstrap
#/ Bootstrap the system by installing the necessary dependencies.
#/ Can be run without cloning the entire repo.
#/
#/ Options
#/   -h, --help   Display this help message.

[ "$debug" == '1' ] && set -x

# Resolve the absolute path of this script's directory.
script_dir=$(dirname $(readlink -f $0))
repo_root=$(dirname $script_dir)

# Parse arguments
while [[ $# -gt 0 ]]; do
  key="$1"
  shift
  case "$key" in
    -h|--help)
      # Print usage information
      grep '^#/' "$0" | cut -c4-
      exit 0
      ;;
    *)
      echo "Unknown option: $key"
      exit 1
      ;;
  esac
done

echo "Bootstrapping system"

is_wsl=false
if [ "$(uname -r | grep -o microsoft)" = "microsoft" ]; then
  is_wsl=true
  export GIT_SSH="ssh.exe"
fi

if ! type systemctl >/dev/null 2>&1; then
  # Set up systemd, if this is WSL
  if $is_wsl; then
    if ! wsl.exe --version >/dev/null 2>&1; then
      echo "WSL version from Microsoft Store is required"
      exit 1
    fi

    if [ -e /etc/wsl.conf ]; then
      if cat /etc/wsl.conf | grep -q "systemd=true"; then
        echo "WSL configured for systemd"
      else
        echo "WSL not configured for systemd"
        echo "Please add the following to /etc/wsl.conf"
        echo "[boot]"
        echo "systemd=true"
        exit 1
      fi
    else
      echo "Creating WSL configuration file"
      sudo tee /etc/wsl.conf <<EOF
[boot]
systemd=true
EOF
      echo "Please restart WSL and re-run this script"
      exit 1
    fi
  else
    echo "Systemd not installed, configure systemd first."
    exit 1
  fi
fi

if ! type nix >/dev/null 2>&1; then
  echo "Installing nix"
  sh <(curl -L https://nixos.org/nix/install) --daemon
fi

# Make sure the 'code' directory and necessary parents exist
parent_dir="$HOME/code/analogrelay"
if ! [ -d "$parent_dir" ]; then
  mkdir -p "$parent_dir"
fi

cd $parent_dir
nix-shell -p git --run "git clone git@github.com:analogrelay/fleet.git"