#!/bin/bash
#/ Usage: script/copy-kv-secret <key-vault-secret-name> <namespace> <secret-name>
#/ Copies the key vault secret named '<key-vault-secret-name>' to a secret named '<secret-name>.value' in the '<namespace>' namespace in the current cluster.

set -e
key_vault_secret_name=$1
namespace=$2
secret_name=$3
key_name=$4

if [ -z "$key_vault_secret_name" ] || [ -z "$namespace" ] || [ -z "$secret_name" ]; then
  grep '^#/' <"$0" | sed 's/^#\/\w*//'
  exit 1
fi

echo "Copying key vault secret '$key_vault_secret_name' to secret '$secret_name.value' in namespace '$namespace'"

# Check if the namespace exists
if ! kubectl get namespace $namespace > /dev/null 2>&1; then
  echo "Creating namespace $namespace"
  kubectl create namespace $namespace
fi

secretValue=$(az keyvault secret show --name $key_vault_secret_name --vault-name analogcompute-vault --query value -o tsv)

if kubectl get secret $secret_name --namespace $namespace > /dev/null 2>&1; then
  echo "Updating existing secret '$secret_name'"
  kubectl delete secret $secret_name --namespace $namespace
fi

kubectl create secret generic $secret_name --namespace $namespace --from-literal=value=$secretValue
