#!/bin/bash

# Fetch the k3s yaml from Key Vault to a temp file
temp_file=$(mktemp)
#trap "rm -f $temp_file" EXIT
az keyvault secret show --vault-name analogcompute-vault --name k3s-config --query value -o tsv > $temp_file

# Rewrite some of the values in the yaml
yq -y -i \
  '.clusters.[0].cluster.server = "https://analogrelay.cloud:6443" | .clusters.[].name = "analogcompute" | .users.[0].name = "analogcompute-ashley" | .contexts.[0].context.cluster = "analogcompute" | .contexts.[0].context.user = "analogcompute-ashley" | .contexts.[0].name = "ashley@analogcompute"' \
  $temp_file

KUBECONFIG=~/.kube/config:$temp_file kubectl config view --flatten > ~/.kube/config.new
mv ~/.kube/config ~/.kube/config.bak
mv ~/.kube/config.new ~/.kube/config