#!/usr/bin/env bash
#/ Usage: script/rebuild [<hostname>] [--test] [--dry-run] [--show-trace]
#/ Rebuild the current system using the latest configuration.
#/
#/ OPTIONS
#/   -h, --help   Display this help message.
#/   --test       Run a 'nixos-rebuild test' instead of a 'nixos-rebuild switch'.
#/   --dry-run    Conduct a dry run and don't actually modify anything.
#/   --show-trace Show a trace whenever there's a Nix error.
#/   --update     Update the flake lockfile before rebuilding.
#/
#/ ARGUMENTS
#/   <hostname>   The hostname of the configuration to use. By default, the value of the `hostname` command is used.
# Resolve the absolute path of this script's directory.
script_dir=$(dirname $(readlink -f $0))
repo_root=$(dirname $script_dir)

# This script is designed to not require the nix shell.

set -euo pipefail

if [ "$(uname)" = "Linux" ]; then
  platform=$(cat /etc/os-release | grep '^ID=' | cut -d'=' -f2)
else
  platform=$(uname)
fi

# Parse arguments
hostname=""
nixos_rebuild_command="switch"
rebuild_args=()
update=false
while [[ $# -gt 0 ]]; do
  key="$1"
  shift
  case "$key" in
    --test)
      nixos_rebuild_command="test"
      ;;
    --dry-run|--show-trace)
      rebuild_args+=($key)
      ;;
    --install-bootloader)
      if [ "$platform" == "nixos" ]; then
        rebuild_args+=("--install-bootloader")
      fi
      ;;
    -h|--help)
      # Print usage information
      grep '^#/' "$0" | cut -c4-
      exit 0
      ;;
    --update)
      update=true
      ;;
    *)
      hostname="$key"
      ;;
  esac
done

if [ -z "$hostname" ]; then
  hostname=$(hostname)
fi

echo "Rebuilding system from configuration for $hostname"
echo "Continue? [y/N]"
read -r answer
if [ "$answer" != "y" ]; then
  echo "Aborting"
  exit 1
fi

if $update; then
  echo "Updating flake lockfile"
  nix flake update
fi

if [ "$(uname)" = "Darwin" ]; then
  if [ "$nixos_rebuild_command" = "test" ]; then
    echo "Running 'nixos-rebuild test' on macOS is not supported."
    exit 1
  fi
  echo "You may be prompted for your sudo password to run the rebuild script."
  sudo darwin-rebuild switch "${rebuild_args[@]}" --flake "$repo_root#$hostname"
else
  if [ "$platform" == "nixos" ]; then
    echo "You may be prompted for your sudo password to run the rebuild script."
    sudo nixos-rebuild switch "${rebuild_args[@]}" --flake "$repo_root#$hostname"
  else
    if ! type -p home-manager >/dev/null 2>&1; then
      # Non-nixos configuration. We support home-manager only.
      if ! nix-channel --list | nix-channel --list | grep home-manager >/dev/null 2>&1; then
        nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
        nix-channel --update
      fi
      nix-shell '<home-manager>' -A install
    fi
    home-manager --extra-experimental-features "nix-command flakes" switch "${rebuild_args[@]}" -b backup --flake ".#$USER@$HOSTNAME"
  fi
fi
