#!/usr/bin/env bash

expected_subscription_id="466cf680-808d-4446-94b3-f367eaa60ba1"
app_id="d7fa9573-9a20-4131-857f-62c1cf35a512"

echo "Validating Azure CLI login..."
if [ $(az account show --query id -o tsv) != $expected_subscription_id ]; then
  echo "Azure CLI is not logged in to the expected subscription."
  exit 1
fi

echo "Resetting Azure credential..."
new_secret=$(az ad app credential reset --id "$app_id" --display-name "Home Kubernetes Credentials" --query password -o tsv)

azure_json_file=$(mktemp)
cat <<EOF > "$azure_json_file"
{
  "tenantId": "2be5c49d-d8ac-4700-a8a7-10668c406a70",
  "subscriptionId": "466cf680-808d-4446-94b3-f367eaa60ba1",
  "resourceGroup": "analogcloud-dns",
  "aadClientId": "d7fa9573-9a20-4131-857f-62c1cf35a512",
  "aadClientSecret": "$new_secret",
}
EOF
trap 'rm -f "$azure_json_file"' EXIT

# Update Kubernetes secrets, and restart services

echo "Updating cert-manager..."
kubectl delete secret --namespace "cert-manager" azuredns-config
kubectl create secret generic --namespace "cert-manager" azuredns-config --from-literal=client-secret="$new_secret"
kubectl rollout restart --namespace "cert-manager" deployment/cert-manager

echo "Updating external-dns..."
kubectl delete secret --namespace "external-dns" azure-config-file
kubectl create secret generic --namespace "external-dns" azure-config-file --from-file=azure.json=$azure_json_file
kubectl rollout restart --namespace "external-dns" deployment/external-dns