- name: Check if SSH enabled
  register: get_remote_login
  become: true
  ansible.builtin.command: systemsetup -getremotelogin

# It's really hard/impossible to enable remote login from command line :(.

- name: Warn that SSH not enabled
  when: "get_remote_login.stdout != 'Remote Login: On'"
  ansible.builtin.fail:
    msg: "SSH is not enabled"
  ignore_errors: true