---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: existing-local-volume
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-avalanche
provisioner: nfs.csi.k8s.io
parameters:
  server: avalanche.home.analogrelay.net
  share: /mnt/data/k3s/shares
  subDir: "${pvc.metadata.namespace}.${pvc.metadata.name}"
  onDelete: retain
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1