---
apiVersion: v1
kind: Namespace
metadata:
  name: cloud-sync
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rclone-config-pv
  namespace: cloud-sync
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: existing-local-volume
  local:
    path: /mnt/data/k3s/volumes/rclone
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - avalanche

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rclone-config-pvc
  namespace: cloud-sync
spec:
  storageClassName: existing-local-volume
  volumeName: rclone-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-onedrive-ashley
  namespace: cloud-sync
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rclone
            image: rclone/rclone:beta
            imagePullPolicy: IfNotPresent
            env:
            - name: RCLONE_CONFIG_PASS
              valueFrom:
                secretKeyRef:
                  name: rclone
                  key: password
            command:
              - rclone
              - sync
              - "--verbose"
              - "onedrive-ashley:"
              - "/target"
            volumeMounts:
              - name: target
                mountPath: /target
              - name: config-file
                mountPath: /config/rclone
          restartPolicy: OnFailure
          volumes:
            - name: target
              nfs:
                server: avalanche.home.analogrelay.net
                path: /mnt/data/shares/public/clouds/onedrive-ashley
            - name: config-file
              persistentVolumeClaim:
                claimName: rclone-config-pvc

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-google-ashley
  namespace: cloud-sync
spec:
  schedule: "15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rclone
            image: rclone/rclone:beta
            imagePullPolicy: IfNotPresent
            env:
            - name: RCLONE_CONFIG_PASS
              valueFrom:
                secretKeyRef:
                  name: rclone
                  key: password
            command:
              - rclone
              - sync
              - "--verbose"
              - "google-ashley:"
              - "/target"
            volumeMounts:
              - name: target
                mountPath: /target
              - name: config-file
                mountPath: /config/rclone
          restartPolicy: OnFailure
          volumes:
            - name: target
              nfs:
                server: avalanche.home.analogrelay.net
                path: /mnt/data/shares/public/clouds/google-ashley
            - name: config-file
              persistentVolumeClaim:
                claimName: rclone-config-pvc

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-onedrive-mary
  namespace: cloud-sync
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rclone
            image: rclone/rclone:beta
            imagePullPolicy: IfNotPresent
            env:
            - name: RCLONE_CONFIG_PASS
              valueFrom:
                secretKeyRef:
                  name: rclone
                  key: password
            command:
              - rclone
              - sync
              - "--verbose"
              - "onedrive-mary:"
              - "/target"
            volumeMounts:
              - name: target
                mountPath: /target
              - name: config-file
                mountPath: /config/rclone
          restartPolicy: OnFailure
          volumes:
            - name: target
              nfs:
                server: avalanche.home.analogrelay.net
                path: /mnt/data/shares/public/clouds/onedrive-mary
            - name: config-file
              persistentVolumeClaim:
                claimName: rclone-config-pvc

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-google-mary
  namespace: cloud-sync
spec:
  schedule: "45 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rclone
            image: rclone/rclone:beta
            imagePullPolicy: IfNotPresent
            env:
            - name: RCLONE_CONFIG_PASS
              valueFrom:
                secretKeyRef:
                  name: rclone
                  key: password
            command:
              - rclone
              - sync
              - "--verbose"
              - "google-mary:"
              - "/target"
            volumeMounts:
              - name: target
                mountPath: /target
              - name: config-file
                mountPath: /config/rclone
          restartPolicy: OnFailure
          volumes:
            - name: target
              nfs:
                server: avalanche.home.analogrelay.net
                path: /mnt/data/shares/public/clouds/google-mary
            - name: config-file
              persistentVolumeClaim:
                claimName: rclone-config-pvc