---
apiVersion: v1
kind: Namespace
metadata:
  name: cloud-sync
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rclone-config-pv
  namespace: cloud-sync
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: existing-local-volume
  local:
    path: /mnt/data/k3s/volumes/rclone
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - avalanche

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rclone-config-pvc
  namespace: cloud-sync
spec:
  storageClassName: existing-local-volume
  volumeName: rclone-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-disk-pv
  namespace: cloud-sync
spec:
  volumeMode: Filesystem
  capacity:
    storage: 14Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: existing-local-volume
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - avalanche

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-disk-pvc
  namespace: cloud-sync
spec:
  storageClassName: existing-local-volume
  volumeName: data-disk-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 14Ti

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-homes
  namespace: cloud-sync
spec:
  schedule: "32 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 5000
          containers:
            - name: rclone
              image: rclone/rclone:beta
              imagePullPolicy: IfNotPresent
              env:
                - name: RCLONE_CONFIG_PASS
                  valueFrom:
                    secretKeyRef:
                      name: rclone
                      key: password
              command:
                - rclone
                - copy
                - "--verbose"
                - "/target/shares/homes"
                - "analogbackup-crypt:"
              volumeMounts:
                - name: target
                  mountPath: /target
                - name: config-file
                  mountPath: /config/rclone
          restartPolicy: OnFailure
          volumes:
            - name: target
              persistentVolumeClaim:
                claimName: data-disk-pvc
            - name: config-file
              persistentVolumeClaim:
                claimName: rclone-config-pvc

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-rest
  namespace: cloud-sync
spec:
  schedule: "32 3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 5000
          containers:
            - name: rclone
              image: rclone/rclone:beta
              imagePullPolicy: IfNotPresent
              env:
                - name: RCLONE_CONFIG_PASS
                  valueFrom:
                    secretKeyRef:
                      name: rclone
                      key: password
              command:
                - rclone
                - copy
                - "--verbose"
                - "--exclude=/shares/homes/**"
                - "--exclude=/k3s/volumes/prometheus/**"
                - "--exclude=/downloads/**"
                - "--exclude=/shares/public/downloads/**"
                - "--exclude=/k3s/shares/frigate.frigate-media/**"
                - "/target"
                - "analogbackup:vault"
              volumeMounts:
                - name: target
                  mountPath: /target
                - name: config-file
                  mountPath: /config/rclone
          restartPolicy: OnFailure
          volumes:
            - name: target
              persistentVolumeClaim:
                claimName: data-disk-pvc
            - name: config-file
              persistentVolumeClaim:
                claimName: rclone-config-pvc

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-onedrive-ashley
  namespace: cloud-sync
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 5000
          containers:
            - name: rclone
              image: rclone/rclone:beta
              imagePullPolicy: IfNotPresent
              env:
                - name: RCLONE_CONFIG_PASS
                  valueFrom:
                    secretKeyRef:
                      name: rclone
                      key: password
              command:
                - rclone
                - sync
                - "--verbose"
                - "onedrive-ashley:"
                - "/target"
              volumeMounts:
                - name: target
                  mountPath: /target
                - name: config-file
                  mountPath: /config/rclone
          restartPolicy: OnFailure
          volumes:
            - name: target
              nfs:
                server: avalanche.node.analogrelay.net
                path: /mnt/data/shares/public/clouds/onedrive-ashley
            - name: config-file
              persistentVolumeClaim:
                claimName: rclone-config-pvc

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-google-ashley
  namespace: cloud-sync
spec:
  schedule: "15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 5000
          containers:
            - name: rclone
              image: rclone/rclone:beta
              imagePullPolicy: IfNotPresent
              env:
                - name: RCLONE_CONFIG_PASS
                  valueFrom:
                    secretKeyRef:
                      name: rclone
                      key: password
              command:
                - rclone
                - sync
                - "--verbose"
                - "google-ashley:"
                - "/target"
              volumeMounts:
                - name: target
                  mountPath: /target
                - name: config-file
                  mountPath: /config/rclone
          restartPolicy: OnFailure
          volumes:
            - name: target
              nfs:
                server: avalanche.node.analogrelay.net
                path: /mnt/data/shares/public/clouds/google-ashley
            - name: config-file
              persistentVolumeClaim:
                claimName: rclone-config-pvc

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-onedrive-mary
  namespace: cloud-sync
spec:
  schedule: "30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 5000
          containers:
            - name: rclone
              image: rclone/rclone:beta
              imagePullPolicy: IfNotPresent
              env:
                - name: RCLONE_CONFIG_PASS
                  valueFrom:
                    secretKeyRef:
                      name: rclone
                      key: password
              command:
                - rclone
                - sync
                - "--verbose"
                - "onedrive-mary:"
                - "/target"
              volumeMounts:
                - name: target
                  mountPath: /target
                - name: config-file
                  mountPath: /config/rclone
          restartPolicy: OnFailure
          volumes:
            - name: target
              nfs:
                server: avalanche.node.analogrelay.net
                path: /mnt/data/shares/public/clouds/onedrive-mary
            - name: config-file
              persistentVolumeClaim:
                claimName: rclone-config-pvc

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-google-mary
  namespace: cloud-sync
spec:
  schedule: "45 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 5000
          containers:
            - name: rclone
              image: rclone/rclone:beta
              imagePullPolicy: IfNotPresent
              env:
                - name: RCLONE_CONFIG_PASS
                  valueFrom:
                    secretKeyRef:
                      name: rclone
                      key: password
              command:
                - rclone
                - sync
                - "--verbose"
                - "google-mary:"
                - "/target"
              volumeMounts:
                - name: target
                  mountPath: /target
                - name: config-file
                  mountPath: /config/rclone
          restartPolicy: OnFailure
          volumes:
            - name: target
              nfs:
                server: avalanche.node.analogrelay.net
                path: /mnt/data/shares/public/clouds/google-mary
            - name: config-file
              persistentVolumeClaim:
                claimName: rclone-config-pvc
