apiVersion: v1
kind: Namespace
metadata:
  name: frigate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: frigate
spec:
  storageClassName: nfs-avalanche
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
  namespace: frigate
spec:
  storageClassName: nfs-avalanche
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: frigatertmp
  namespace: frigate

spec:
  entryPoints:
    - rtmp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: frigate
          port: rtmp

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: frigatertsp
  namespace: frigate

spec:
  entryPoints:
    - rtsp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: frigate
          port: rtsp

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: frigate
  namespace: kube-system
spec:
  repo: https://blakeblackshear.github.io/blakeshome-charts/
  chart: frigate
  targetNamespace: frigate
  version: 7.3.0
  valuesContent: |-
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
      hosts:
        - host: frigate.home.analogrelay.net
          paths:
            - '/'
      tls:
        - hosts:
            - frigate.home.analogrelay.net
          secretName: frigate-ingress-cert
    persistence:
      config:
        enabled: true
        existingClaim: frigate-config
      media:
        enabled: true
        existingClaim: frigate-media
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - shinra 
    coral:
      enabled: true
    envFromSecrets:
      - "secret-envs"
    config: |
      detectors:
        coral:
          type: edgetpu
          device: usb
      objects:
        track:
          - person
          - car
          - cat
          - dog
      mqtt:
        host: "home.analogrelay.net"
        port: 1883
      record:
        enabled: true
        retain:
          days: 3
          mode: all
        events:
          retain:
            default: 30
            mode: motion
      go2rtc:
        streams:
          frontdoorbell:
            - "rtsp://admin:{FRIGATE_RTSP_PASSWORD}@frontdoorbell.node.analogrelay.net/cam/realmonitor?channel=1&subtype=0"
          driveway:
            - "rtsp://admin:{FRIGATE_RTSP_PASSWORD}@drivewaycam.node.analogrelay.net/live0"
      cameras:
        frontdoorbell:
          enabled: true
          objects:
            filters:
              car:
                mask:
                  - 631,0,737,307,741,250,533,311,522,422,339,404,127,418,0,416,0,0
              person:
                mask:
                  - 631,0,737,307,741,250,533,311,522,422,339,404,127,418,0,416,0,0
          motion:
            mask:
              - 631,0,737,307,741,250,533,311,522,422,339,404,127,418,0,416,0,0
          zones:
            porch:
              coordinates: 824,720,812,661,528,644,423,720
          ffmpeg:
            inputs:
              - path: "rtsp://admin:{FRIGATE_RTSP_PASSWORD}@frontdoorbell.node.analogrelay.net/cam/realmonitor?channel=1&subtype=0&unicast=true"
                roles:
                  - record
              - path: "rtsp://admin:{FRIGATE_RTSP_PASSWORD}@frontdoorbell.node.analogrelay.net/cam/realmonitor?channel=1&subtype=1&unicast=true"
                roles:
                  - detect
        driveway:
          enabled: true
          motion:
            mask:
              - 1280,0,1259,169,975,120,679,120,535,129,379,132,159,148,0,186,0,0
          objects:
            filters:
              car:
                mask:
                  - 1280,0,1280,172,969,118,685,123,377,136,0,181,0,0
              person:
                mask:
                  - 1280,0,1280,172,969,118,685,123,377,136,0,181,0,0
          zones:
            parking_left:
              coordinates: 310,177,614,183,600,573,22,512
            parking_right:
              coordinates: 707,482,1131,449,937,142,667,180
          ffmpeg:
            inputs:
              - path: "rtsp://admin:{FRIGATE_RTSP_PASSWORD}@drivewaycam.node.analogrelay.net/live0"
                roles:
                  - record
              - path: "rtsp://admin:{FRIGATE_RTSP_PASSWORD}@drivewaycam.node.analogrelay.net/live1"
                roles:
                  - detect
