apiVersion: v1
kind: Namespace
metadata:
  name: icloudpd

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: icloud-backups-pv
  namespace: icloudpd
spec:
  volumeMode: Filesystem
  capacity:
    storage: 14Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: existing-local-volume
  local:
    path: /mnt/data/shares/public/backups/icloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - avalanche

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icloud-backups-pvc
  namespace: icloudpd
spec:
  storageClassName: existing-local-volume
  volumeName: icloud-backups-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 14Ti

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: icloudpd-launch-script
  namespace: icloudpd
data:
  launch.sh: |-
    #!/bin/sh
    /app/icloudpd_ex icloudpd \
      --directory "/data/$DIRNAME" \
      --cookie-directory "/data/.auth/$DIRNAME/cookies" \
      --username "$APPLE_USERNAME" \
      --password-provider keyring \
      --size original \
      --smtp-username "$SMTP_USERNAME" \
      --smtp-password "$SMTP_PASSWORD" \
      --smtp-host smtp.fastmail.com \
      --watch-with-interval 3600

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icloud-backup-ashley
  namespace: icloudpd
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: icloud-backup-ashley
  template:
    metadata:
      labels:
        app: icloud-backup-ashley
    spec:
      securityContext:
        fsGroup: 5000
      containers:
        - name: icloudpd
          image: icloudpd/icloudpd:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: DIRNAME
              value: "ashley"
            - name: XDG_DATA_HOME
              value: "/data/.auth/ashley"
            - name: APPLE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: icloudpd-apple-ashley
                  key: username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icloudpd-smtp
                  key: password
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: icloudpd-smtp
                  key: username
          command:
            - "/script/launch.sh"
          volumeMounts:
            - name: target-vol
              mountPath: /data
            - name: script-vol
              mountPath: /script
      volumes:
        - name: target-vol
          persistentVolumeClaim:
            claimName: icloud-backups-pvc
        - name: script-vol
          configMap:
            name: icloudpd-launch-script
            defaultMode: 0744
