---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: postgres
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: existing-local-volume
  local:
    path: /var/volumes/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shinra

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgres
spec:
  storageClassName: existing-local-volume
  volumeName: postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels: 
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:16.1
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: root-password
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: postgres
  annotations:
    external-dns.alpha.kubernetes.io/hostname: db.home.analogrelay.net
spec:
  type: LoadBalancer
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres 
    protocol: TCP
  selector:
    app: postgres
