apiVersion: v1
kind: Namespace
metadata:
  name: tailscale

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tailscale
  namespace: kube-system
spec:
  repo: https://pkgs.tailscale.com/helmcharts
  chart: tailscale-operator
  targetNamespace: tailscale

---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: k3s-home-connector
spec:
  hostname: k3s-home
  subnetRouter:
    advertiseRoutes:
      - "10.42.0.0/16"
      - "10.43.0.0/16"