apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--serverstransport.insecureskipverify=true"
      - "--entrypoints.mqtt.address=:1883/tcp"
      - "--entrypoints.mqttws.address=:9001/tcp"
      - "--entrypoints.postgres.address=:5432/tcp"
      - "--providers.file.filename=/config/additional.toml"
    volumes:
      - name: traefik-toml-config
        mountPath: /config
        type: configMap
      - name: home-cert-tls
        mountPath: /certs/home
        type: secret
      - name: octoprint-cert-tls
        mountPath: /certs/octoprint
        type: secret
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: octoprint-cert
  namespace: kube-system
spec:
  secretName: octoprint-cert-tls
  dnsNames:
    - octoprint.home.analogrelay.net
    - octoprint-cam.home.analogrelay.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - digital signature
    - key encipherment

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-cert
  namespace: kube-system
spec:
  secretName: home-cert-tls
  dnsNames:
    - home.analogrelay.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - digital signature
    - key encipherment

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-toml-config
  namespace: kube-system
data:
  additional.toml: |
    [tls]
      [[tls.certificates]]
        certFile = "/certs/home/tls.crt"
        keyFile = "/certs/home/tls.key"
      [[tls.certificates]]
        certFile = "/certs/octoprint/tls.crt"
        keyFile = "/certs/octoprint/tls.key"

    [http]
      [http.routers]
        [http.routers.web-home-assistant]
          rule = "Host(`home.analogrelay.net`) && PathPrefix(`/`)"
          entryPoints = ["web"]
          service = "home-assistant"
          middlewares = ["kube-system-redirect@kubernetescrd"]
        [http.routers.websecure-home-assistant]
          rule = "Host(`home.analogrelay.net`) && PathPrefix(`/`)"
          entryPoints = ["websecure"]
          service = "home-assistant"
          middlewares = ["kube-system-redirect@kubernetescrd"]
          [http.routers.websecure-home-assistant.tls]

        [http.routers.web-octoprint]
          rule = "Host(`octoprint.home.analogrelay.net`) && PathPrefix(`/`)"
          entryPoints = ["web"]
          service = "octoprint"
          middlewares = ["kube-system-redirect@kubernetescrd"]
        [http.routers.websecure-octoprint]
          rule = "Host(`octoprint.home.analogrelay.net`) && PathPrefix(`/`)"
          entryPoints = ["websecure"]
          service = "octoprint"
          middlewares = ["kube-system-redirect@kubernetescrd"]
          [http.routers.websecure-octoprint.tls]

        [http.routers.websecure-octoprint-camera]
          rule = "Host(`octoprint-cam.home.analogrelay.net`) && PathPrefix(`/`)"
          entryPoints = ["websecure"]
          service = "octoprint-camera"
          middlewares = ["kube-system-redirect@kubernetescrd"]
          [http.routers.websecure-octoprint-camera.tls]

      [http.services]
        [http.services.home-assistant]
          [http.services.home-assistant.loadBalancer]
            [[http.services.home-assistant.loadBalancer.servers]]
              url = "http://home.node.analogrelay.net:8123"
        [http.services.octoprint]
          [http.services.octoprint.loadBalancer]
            [[http.services.octoprint.loadBalancer.servers]]
              url = "http://wedge.node.analogrelay.net:5000"
        [http.services.octoprint-camera]
          [http.services.octoprint-camera.loadBalancer]
            [[http.services.octoprint-camera.loadBalancer.servers]]
              url = "http://wedge.node.analogrelay.net:8001"
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik-dashboard
spec:
  type: ClusterIP
  ports:
  - name: traefik
    port: 80
    targetPort: traefik
    protocol: TCP
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard-in
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: traefik.home.analogrelay.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik-dashboard
            port:
              number: 80
  tls:
    - hosts:
        - traefik.home.analogrelay.net
      secretName: traefik-ingress-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard-ts
  namespace: kube-system
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: traefik-dashboard
      port:
        number: 80
  tls:
    - hosts:
        - traefik

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: kube-system
spec:
  redirectScheme:
    scheme: https
    permanent: true